version: "3"

services:
  db-competitions:
    container_name: competitions_database
    image: mysql:8.4.1
    restart: always
    volumes:
      - competitions-mysql-data:/var/lib/mysql
    ports:
      - "3308:3306"
    environment:
      - MYSQL_ROOT_PASSWORD=password
      - MYSQL_DATABASE=competitions_db

volumes:
  competitions-mysql-data: